# Generated by Django 4.0.4 on 2022-06-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('cursos', models.CharField(choices=[('Técnico em Informática para Internet', 'Técnico em informática para Internet'), ('Técnico em Agropecuaria', 'Técnico em Agropecuaria'), ('Técnico em Agroindustria', 'Técnico em Agroindustria')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
