# Generated by Django 4.0.4 on 2022-06-05 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, null=True)),
                ('CNPJ', models.IntegerField(null=True)),
                ('contato', models.IntegerField(null=True)),
                ('rua', models.CharField(max_length=120, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('bairro', models.CharField(max_length=120, null=True)),
                ('CEP', models.IntegerField(null=True)),
                ('razaosocial', models.CharField(max_length=70, null=True, verbose_name='Razão Social')),
                ('userEmpresa', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
